# Generated by Django 4.0.3 on 2022-03-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_created_tag_model_and_added_relationship_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='posts.tag'),
        ),
    ]
